name: Test MATLAB Bindings

on: [push]

env:
  LD_LIBRARY_PATH: /lib/x86_64-linux-gnu/libstdc++.so.6

jobs:
  build:
    name: Test MATLAB Bindings
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
            release: R2023b
      - name: Check out repository
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install dependencies
        run: |
            sudo apt-get -qq update
            sudo apt-get install -y git cmake graphviz libavahi-common-dev libavahi-client-dev libaio-dev libusb-1.0-0-dev libxml2-dev rpm tar bzip2 gzip flex bison git libzstd-dev
            echo "IIO_EMU_PREFIX='LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/libstdc++.so.6'" >> $GITHUB_ENV
            cmake . -DHAVE_DNS_SD=OFF
            make
            sudo make install
            mkdir edeps
            cd edeps
            git clone https://github.com/analogdevicesinc/libtinyiiod.git
            cd libtinyiiod
            mkdir build && cd build
            cmake -DBUILD_EXAMPLES=OFF ..
            make
            sudo make install
            sudo ldconfig
            cd ../..
            git clone -b v0.1.0 https://github.com/analogdevicesinc/iio-emu.git
            cd iio-emu
            mkdir build && cd build
            cmake ..
            make
            sudo make install
            sudo ldconfig
            cd ../..
            cd ..

      - name: Run Tests
        uses: matlab-actions/run-command@v2
        with:
            command: addpath(genpath('include'));cd('bindings/matlab');addpath(genpath('.'));runTests;exit()
